version: '3.7'

services:
	base:
		env_file: ./.env
		restart: always
		extra_hosts:
			- "jsiona.42.fr:127.0.0.1"

	nginx:
		extends: 
			service: base
		depends_on:
			- wordpress
		ports:
			- "443:443"
		build:
			context: ./requirements/nginx
			dockerfile: Dockerfile

		# networks:
			# - wordpress


		# volumes:
			# - .:/var/www/html

		# command:
		# image:

networks:
	localhost:
		driver: "bridge"

volumes: 
	mysqldata:
		driver: "local"
