version: '3.7'

services:
  nginx: 
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped

    ports: 
      - 443:443
    env_file:
      - .env
    networks: 
      - localhost
    depends_on: 
      - wordpress
    volumes: 
      - web-root:/var/www/wordpress
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped

    env_file:
      - .env
    networks: 
      - localhost
    depends_on: 
      - mariadb
    volumes:
      - web-root:/var/www/wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped

    env_file:
      - .env
    networks: 
      - localhost
    volumes:
      - sql-root:/var/lib/mysql

volumes: 
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ~/data/web
      o: bind
  sql-root:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

networks:
  localhost:
    driver: bridge
    name: app-network

