version: '3.7'

services:
  nginx: 
    build: ./requirements/nginx
    container_name: webserver
    restart: unless-stopped
    env_file: ./.env

    ports: 
      - 443:443
    networks: 
      - localhost
    # depends_on: 
    #   - wordpress
    volumes: 
      - web-root:/var/www/html
    extra_hosts:
      - jsiona.42.fr:127.0.0.1



volumes: 
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/jsiona/data/web
      o: bind


networks:
  localhost:
    driver: bridge
    name: app-network

