version: '3.7'

services:
  nginx: 
    build: ./requirements/nginx
    container_name: webserver
    restart: unless-stopped

    ports: 
      - 443:443
    networks: 
      - localhost
    depends_on: 
      - wordpress
    volumes: 
      - web-root:/var/www/wordpress
    extra_hosts:
      - jsiona.42.fr:127.0.0.1

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped

    networks: 
      - localhost
    depends_on: 
      - mariadb
    volumes:
      - web-root:/var/www/wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped

    networks: 
      - localhost
    volumes:
      - mysql:/var/lib/mysql

volumes: 
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/jsiona/data/web
      o: bind
  mysql:
    driver: local
    driver_opts:
      type: none
      device: /home/jsiona/data/mariadb
      o: bind

networks:
  localhost:
    driver: bridge
    name: app-network

